### ISSUE TITLE
Submit to native.directory and js.coach

### ISSUE THREAD

**Issue by Noitidart** [everdrone/react-native-super-ellipse-mask#5]
This is a superb module and isn't getting enough attention. We should share to js.coach and native.directory as I did here - https://github.com/rajsuvariya/autocompletetextview/issues/7

**Comment by everdrone** [comment]
Hi @Noitidart, thanks for the kind words! 😀

I just submitted a [Pull Request](https://github.com/react-community/native-directory/pull/132) for native.directory and an [Issue](https://github.com/jscoach/support/issues/819) for js.coach

**Comment by Noitidart** [comment]
Thank you!!
